// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsOxP5xVzpBkKcPfYJ-IhuzQsSaKPTvYU',
    appId: '1:831379715626:web:13369e4fdbc2726b10f553',
    messagingSenderId: '831379715626',
    projectId: 'amala-38336',
    authDomain: 'amala-38336.firebaseapp.com',
    storageBucket: 'amala-38336.firebasestorage.app',
    measurementId: 'G-RK4EMN8943',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaa-dj5hFhw5H2yziBvG-8py90YyFpI4s',
    appId: '1:865959042909:android:63eebd9a1cc0bbed2912b4',
    messagingSenderId: '865959042909',
    projectId: 'phoneauth-7b0d1',
    storageBucket: 'phoneauth-7b0d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN2UmZaC4b_RYacZev0UynsYoDjEyDgxA',
    appId: '1:865959042909:ios:f9562458a26e81c42912b4',
    messagingSenderId: '865959042909',
    projectId: 'phoneauth-7b0d1',
    storageBucket: 'phoneauth-7b0d1.firebasestorage.app',
    iosBundleId: 'com.example.leadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4hpJQMxfKql8tR7u_QWdFLnHVNYgAm00',
    appId: '1:831379715626:ios:eb97bee37c651ed410f553',
    messagingSenderId: '831379715626',
    projectId: 'amala-38336',
    storageBucket: 'amala-38336.firebasestorage.app',
    iosBundleId: 'com.example.labourBazaar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsOxP5xVzpBkKcPfYJ-IhuzQsSaKPTvYU',
    appId: '1:831379715626:web:b91ef0c191616fd910f553',
    messagingSenderId: '831379715626',
    projectId: 'amala-38336',
    authDomain: 'amala-38336.firebaseapp.com',
    storageBucket: 'amala-38336.firebasestorage.app',
    measurementId: 'G-V9QD1LXNRL',
  );
}